**Exercise 1**:

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [10]:
import numpy as np

arr = np.arange(1,11)
print("The array is:\n", arr)

matrix= arr.reshape(2,5)
print("The reshaped matrix is:\n",matrix)

The array is:
 [ 1  2  3  4  5  6  7  8  9 10]
The reshaped matrix is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Exercise 2**:

Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [12]:
import numpy as np

arr = np.arange(1,21)
print("The array is \n",arr)

extracted_array= arr[5:15]
print("The extracted array is \n",extracted_array)

The array is 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The extracted array is 
 [ 6  7  8  9 10 11 12 13 14 15]


**Exercise 3**:

Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [21]:
import pandas as pd

fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print("The series of fruits is \n",fruits,"\n")

fruits['Pears']=4
print("The new series of fruits is \n",fruits)

The series of fruits is 
 apples     3
bananas    2
oranges    1
dtype: int64 

The new series of fruits is 
 apples     3
bananas    2
oranges    1
Pears      4
dtype: int64


**Exercise 4:**

Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [34]:
import pandas as pd

data={
    'Name':['John','Victor','Gopan','Manoj','Mohan','Antony','Sneha','Binoy','Megha','Deepa'],
    'Age':[25, 30, 22, 28, 26, 35, 24, 29, 27, 32],
    'Gender':['Male','Male','Male','Male','Male','Male','Female','Male','Female','Female']
    }
df = pd.DataFrame(data)
print(df)

     Name  Age  Gender
0    John   25    Male
1  Victor   30    Male
2   Gopan   22    Male
3   Manoj   28    Male
4   Mohan   26    Male
5  Antony   35    Male
6   Sneha   24  Female
7   Binoy   29    Male
8   Megha   27  Female
9   Deepa   32  Female


**Exercise 5**:

Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [35]:
occupations=[ 'Programmer', 'Manager', 'Analyst',' Programmer', 'Manager','Analyst' ,'Programmer', 'Manager','Analyst','Programmer']
df['Occupation']=occupations
print(df)

     Name  Age  Gender   Occupation
0    John   25    Male   Programmer
1  Victor   30    Male      Manager
2   Gopan   22    Male      Analyst
3   Manoj   28    Male   Programmer
4   Mohan   26    Male      Manager
5  Antony   35    Male      Analyst
6   Sneha   24  Female   Programmer
7   Binoy   29    Male      Manager
8   Megha   27  Female      Analyst
9   Deepa   32  Female   Programmer



**Exercise 6:**

Select the rows of the dataframe where the age is greater than or equal to 30


In [31]:
print("People with age greater than or equal to 30 \n",df[df['Age']>=30])

People with age greater than or equal to 30 
      Name  Age  Gender  Occupation
1  Victor   30    Male     Manager
5  Antony   35    Male     Analyst
9   Deepa   32  Female  Programmer


**Exercise 7**:

Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [42]:
df.to_csv("data.csv",index=False)
read_df=pd.read_csv("data.csv")
print(read_df)

     Name  Age  Gender   Occupation
0    John   25    Male   Programmer
1  Victor   30    Male      Manager
2   Gopan   22    Male      Analyst
3   Manoj   28    Male   Programmer
4   Mohan   26    Male      Manager
5  Antony   35    Male      Analyst
6   Sneha   24  Female   Programmer
7   Binoy   29    Male      Manager
8   Megha   27  Female      Analyst
9   Deepa   32  Female   Programmer
